### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by gkuberreddy** [qiqiApink/MotionGPT#17]
I use Python 3.9 and Ubuntu 22.04.3!

I get the error for "import pyrender" : AttributeError: 'NoneType' object has no attribute 'glGetError'

I have a PyopenGL version:  3.1.7

Any leads on how do I solve this? Has anyone faced the similar issue?

**Comment by will-wang19** [comment]
> I use Python 3.9 and Ubuntu 22.04.3!
> 
> I get the error for "import pyrender" : AttributeError: 'NoneType' object has no attribute 'glGetError'
> 
> I have a PyopenGL version: 3.1.7
> 
> Any leads on how do I solve this? Has anyone faced the similar issue?

hello, I met the same problem. I solved it by these steps:
1. found the python file in your conda env '..../site-packages/OpenGL/raw/GL/_errors.py' and changed both _error_checker=None;like this [link](https://github.com/brjathu/PHALP/issues/7)
2. change os.environ['PYOPENGL_PLATFORM'] = "osmesa" to os.environ['PYOPENGL_PLATFORM'] = "egl"

**Comment by gkuberreddy** [comment]
> > I use Python 3.9 and Ubuntu 22.04.3!
> > I get the error for "import pyrender" : AttributeError: 'NoneType' object has no attribute 'glGetError'
> > I have a PyopenGL version: 3.1.7
> > Any leads on how do I solve this? Has anyone faced the similar issue?
> 
> hello, I met the same problem. I solved it by these steps:
> 
> 1. found the python file in your conda env '..../site-packages/OpenGL/raw/GL/_errors.py' and changed both _error_checker=None;like this [link](https://github.com/brjathu/PHALP/issues/7)
> 2. change os.environ['PYOPENGL_PLATFORM'] = "osmesa" to os.environ['PYOPENGL_PLATFORM'] = "egl"

Great, this worked! Thanks you @will-wang19
