### ISSUE TITLE
Out of Memory Error in Evaluation LLAMA  

### ISSUE THREAD

**Issue by SHUWEI-HO** [qiqiApink/MotionGPT#4]
Hello, when I was executing evaluate llama with the loading of the llama model (7B), I encountered an out of memory error. I noticed that during the previous fine-tune training, I also had loading, but this issue did not occur. Could you please tell me what is the reason that  makes  this error happen?

**Comment by qiqiApink** [comment]
Maybe it is because the bfloat16 is used in training but not used in evaluation. You can refer to the training code to modify and try again.

**Comment by SHUWEI-HO** [comment]
Got it ! Thank you for your response.

**Comment by bruinxiong** [comment]
> 

how did you solve this issue ?  I met the same problem. Thanks!

**Comment by bruinxiong** [comment]
> Got it ! Thank you for your response.

@SHUWEI-HO 

how did you solve this issue ? I met the same problem. Thanks!

**Comment by SHUWEI-HO** [comment]
with fabric.device, lora(r=args.lora_r, alpha=args.lora_alpha, dropout=args.lora_dropout, enabled=True):
        config = LLaMAConfig.from_name(args.pretrained_llama)
        torch.set_default_tensor_type(torch.HalfTensor)
        model = LLaMA(config).bfloat16()
        torch.set_default_tensor_type(torch.FloatTensor)

**Comment by gkuberreddy** [comment]
What if my GPU doesn't support bfloat16() precision?
How do I change and which lines to change to work with LoRA finetuning?
