### ISSUE TITLE
About the demo of generation_motion.py

### ISSUE THREAD

**Issue by SHUWEI-HO** [qiqiApink/MotionGPT#5]
Hello!I tried the  demo by using  "python generate_motion.py --prompt "Generate a sequence of motion tokens matching the following human motion description." --input "a person walks forward." --lora_path ./checkpoints/pretrained_lora/pretrained.pth --out_dir {output_dir}" this command , and the system response me the ValueError: (  invalid literal for int() with base 10: 'Input: a person walks forward. Output: a sequence of tokens that:\n\n  * begins with the person token\n  * ends with the person token\n  * has a ground token in between each motion (i.e.' ) in line 114  "tokens = torch.tensor([int(token) for token in output.split(',')]).cuda()". Do the tokens need to be encoded using the tokenizer.encode in tokenizer.py, or are there other ways to convert the tokens to integers?"

**Comment by felipe-parodi** [comment]
Were you able to resolve this?

**Comment by SHUWEI-HO** [comment]
You can try to copy the code (try except) in evaluate.py into generation.py and then adjust the temperature of generation.py from 0.8 to 4.0. Although this does not guarantee that it will produce an action that matches the content of our input, it can still present a general action.

**Comment by SHUWEI-HO** [comment]
This problem was solved .

**Comment by RalphHan** [comment]
> 

My output (temperature=4.0) is:
```
Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
Generate a sequence of motion tokens matching the following human motion description.

### Input:
a person walks forward.

### Response: [[input 'data frame'>, open tiff ('mov tf from Piv']!METHOD5_(C('imgDATAVUE|wgtID'))>//...5SampleList4Possible (output('datap
```
Where "Response" is not a list of integers split with comma as expected.
